service: ${env:GITHUB_REPOSITORY}

frameworkVersion: "2"
variablesResolutionMode: 20210326

plugins:
  - serverless-python-requirements
  - serverless-deployment-bucket

custom:
  pythonRequirements:
    dockerizePip: non-linux

  stage: "${self:provider.stage}"


provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION, 'us-west-2'}
  runtime: python3.8
  lambdaHashingVersion: 20201221
  # Add IAM permissions for your Lambda Function as needed:
  # iam:
  #   role:
  #     statements:
  #       - Effect: 'Allow'
  #         Action:
  #           - 'translate:TranslateText'
  #         Resource: "*"
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal:
            AWS: "arn:aws:sts::${aws:accountId}:assumed-role/${env:SNOWFLAKE_IAM_ROLE, 'SnowflakeExternalFunctionsRole'}/snowflake"
        Action: execute-api:Invoke
        Resource:
          - arn:aws:execute-api:${aws:region}:${aws:accountId}:*

package:
  exclude:
    - .git/**
    - .env/**
    - node_modules/**

functions:
  SnowflakeExternalFunction:
    handler: lambda_function.handler
    events:
      - http:
          path: /external_function
          method: post
          authorizer: aws_iam
    timeout: 30
    memorySize: 1024